### DataFrames 2

###  1. Conditional Selection: 
    #A very important feature of pandas is the ability to perform conditional selection using bracket notation similar 
    to Numpy
#### 2. Multiple conditional selection with Ampersand & for and and | for or to avoid the ambiguity of the boolean 
#### 3. df.set_index() to a new  index and df.reset_index() to reset index with the numerical indices

In [1]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [2]:
# Create a DataFrame : DataFrame([data, index, columns, dtype, copy])
np.random.seed(10) # set the random seed to keep the same ramdom number 
data=randn(4,5)  # use randint() to create a 5x6 array with random number
print(data)
#arr=np.array(['A,B,C,D,E,F'])
Column='A B C D F'.split()  #  string.splt() will create a list
print(Column)




[[ 1.3315865   0.71527897 -1.54540029 -0.00838385  0.62133597]
 [-0.72008556  0.26551159  0.10854853  0.00429143 -0.17460021]
 [ 0.43302619  1.20303737 -0.96506567  1.02827408  0.22863013]
 [ 0.44513761 -1.13660221  0.13513688  1.484537   -1.07980489]]
['A', 'B', 'C', 'D', 'F']


In [3]:
labels='0 1 2 3'.split()
df=pd.DataFrame(data,labels, Column)
df

A         B         C         D         F
0  1.331587  0.715279 -1.545400 -0.008384  0.621336
1 -0.720086  0.265512  0.108549  0.004291 -0.174600
2  0.433026  1.203037 -0.965066  1.028274  0.228630
3  0.445138 -1.136602  0.135137  1.484537 -1.079805

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df.describe()

A         B         C         D         F
count  4.000000  4.000000  4.000000  4.000000  4.000000
mean   0.372416  0.261806 -0.566695  0.627180 -0.101110
std    0.841136  1.007822  0.829676  0.750082  0.728904
min   -0.720086 -1.136602 -1.545400 -0.008384 -1.079805
25%    0.144748 -0.085017 -1.110149  0.001123 -0.400901
50%    0.439082  0.490395 -0.428259  0.516283  0.027015
75%    0.666750  0.837219  0.115196  1.142340  0.326807
max    1.331587  1.203037  0.135137  1.484537  0.621336

In [6]:
df>0 # condition where values>0 in df results a boolean

A      B      C      D      F
0   True   True  False  False   True
1  False   True   True   True  False
2   True   True  False   True   True
3   True  False   True   True  False

In [7]:
df[df>0]  # use this boolean in [] for contional selection

A         B         C         D         F
0  1.331587  0.715279       NaN       NaN  0.621336
1       NaN  0.265512  0.108549  0.004291       NaN
2  0.433026  1.203037       NaN  1.028274  0.228630
3  0.445138       NaN  0.135137  1.484537       NaN

In [8]:
# Now I dont want to have NaN values do I will specify to a column where 
df[df['A']>0]

A         B         C         D         F
0  1.331587  0.715279 -1.545400 -0.008384  0.621336
2  0.433026  1.203037 -0.965066  1.028274  0.228630
3  0.445138 -1.136602  0.135137  1.484537 -1.079805

In [9]:
df[df['B']>0]

A         B         C         D         F
0  1.331587  0.715279 -1.545400 -0.008384  0.621336
1 -0.720086  0.265512  0.108549  0.004291 -0.174600
2  0.433026  1.203037 -0.965066  1.028274  0.228630

###  Multiple conditional selection with Ampersand & for and and | for or to avoid the ambiguity of the boolean

In [10]:
# join these two condition together using Amphsand & for and , for or 
df[(df['B']>0) & (df['A']>0)]   # comparing two booleans inside the bracket

A         B         C         D         F
0  1.331587  0.715279 -1.545400 -0.008384  0.621336
2  0.433026  1.203037 -0.965066  1.028274  0.228630

In [11]:
df[df['A']>0]["B"]  # find the B columns in the  subset of the dataframe where all values>0 in A intersect 

0    0.715279
2    1.203037
3   -1.136602
Name: B, dtype: float64

In [12]:
df[df['A']>0]

A         B         C         D         F
0  1.331587  0.715279 -1.545400 -0.008384  0.621336
2  0.433026  1.203037 -0.965066  1.028274  0.228630
3  0.445138 -1.136602  0.135137  1.484537 -1.079805

In [13]:
df.iloc[2,3]  # value on 3rd rwo and 4th column

1.028274077982704

In [14]:
bool1=df['A']>0
bool2=df['D']<0
df[bool1 & bool2]

A         B       C         D         F
0  1.331587  0.715279 -1.5454 -0.008384  0.621336

In [15]:
df[bool1 | bool2]

A         B         C         D         F
0  1.331587  0.715279 -1.545400 -0.008384  0.621336
2  0.433026  1.203037 -0.965066  1.028274  0.228630
3  0.445138 -1.136602  0.135137  1.484537 -1.079805

### 3. df.set_index() to a new index and df.reset_index() to reset index with the numerical indices

In [16]:
# create a new index 
A='F M F M'.split()  # a new list 
A

['F', 'M', 'F', 'M']

In [17]:
df['Gender']=A  # create a new column

In [18]:
df

A         B         C         D         F Gender
0  1.331587  0.715279 -1.545400 -0.008384  0.621336      F
1 -0.720086  0.265512  0.108549  0.004291 -0.174600      M
2  0.433026  1.203037 -0.965066  1.028274  0.228630      F
3  0.445138 -1.136602  0.135137  1.484537 -1.079805      M

In [19]:
# DataFrame.set_index(keys, drop=True, append=False, inplace=False, verify_integrity=False)
# parameter: key: This parameter can be either a single column key, a single array of the same length as the calling DataFrame,
        #or a list containing an arbitrary combination of column keys and arrays

In [20]:
# set this new column as new index
df.set_index('Gender')

A         B         C         D         F
Gender                                                  
F       1.331587  0.715279 -1.545400 -0.008384  0.621336
M      -0.720086  0.265512  0.108549  0.004291 -0.174600
F       0.433026  1.203037 -0.965066  1.028274  0.228630
M       0.445138 -1.136602  0.135137  1.484537 -1.079805

In [21]:
# Reset_index: DataFrame.reset_index(level=None, drop=False, inplace=False, col_level=0, col_fill='')

In [22]:
df.reset_index()

index         A         B         C         D         F Gender
0     0  1.331587  0.715279 -1.545400 -0.008384  0.621336      F
1     1 -0.720086  0.265512  0.108549  0.004291 -0.174600      M
2     2  0.433026  1.203037 -0.965066  1.028274  0.228630      F
3     3  0.445138 -1.136602  0.135137  1.484537 -1.079805      M

In [23]:
df.reset_index(drop=True) # We can use the drop parameter to avoid the old index being added as a column

A         B         C         D         F Gender
0  1.331587  0.715279 -1.545400 -0.008384  0.621336      F
1 -0.720086  0.265512  0.108549  0.004291 -0.174600      M
2  0.433026  1.203037 -0.965066  1.028274  0.228630      F
3  0.445138 -1.136602  0.135137  1.484537 -1.079805      M

In [24]:
df.shape

(4, 6)